- src/components/card/__tests__/card-test-cases.js
When I merged the two card types into one in #17, I forgot to add a test case for a `Card` without an image.
> Add test case for Card with no image

- package-lock.json
- package.json
- src/components/product-menu/product-menu.js
After chatting with @davidtheclark, it seems that the best way to handle the custom class in this component is by inlining the style we need instead of relying on a class from some external CSS. Thankfully, `react-popover` has a handy `contentElementAttributes` we can use to do just that! 
It looks like `react-popover` also sets a default `backgroundColor` and setting your own `contentElementAttributes` overwrites that default. I am setting the `backgroundColor` explicitly here and may be missing some other, more crafty way to keep that default value! 
Also noticed that I broke package.json with my last PR, so _this_ PR fixes it 😓
> Remove product menu class

- package-lock.json
- package.json
- src/components/examples-page/examples-page.js
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/page-layout.js
- src/data/product-menu-items.js
Closes #32 
1️⃣ `PageLayout` allows different `top` props for wide and narrow screens. 
2️⃣ `ExamplesPage` no longer includes a title. That should be the responsibility of the PageShell. 
3️⃣ "Mapbox Studio manual" --> "Mapbox Studio" and move to the Maps section of the `ProductMenu`.
> Improve existing components

- src/components/book-image/book-image.js
- src/components/booklet-image/booklet-image.js
- src/components/booklet-image/index.js
- src/components/contact-image/contact-image.js
- src/components/contact-image/index.js
- src/components/note/__tests__/note-test-cases.js
- src/components/troubleshoot-image/index.js
- src/components/troubleshoot-image/troubleshoot-image.js
Variety is the spice of life. These little images spice up dr-ui's selection of cute SVGs. 
I've also added a `height` and `width` prop to all of the images so they can be more easily sized without resorting to dark magic.
> Adds lil booklet, contact, and troubleshoot images

- CHANGELOG.md
- src/components/navigation-accordion/navigation-accordion.js
Fixes #40 
@davidtheclark this was happening because I was feeding the `secondLevelItems` prop an empty array. I'm not sure if this is something that should be prevented here or in the documentation style guide itself.
> Prevent extra whitespace in NavigationAccordion for pages with no headings

- CHANGELOG.md
- src/data/product-menu-items.js
Closes #47.
Do you like it in "More"? Or did you have another place in mind?
@HeyStenson for review, please. We shouldn't merge too eagerly, though, since we don't want this out before the Atlas Server docs page.
cc @mapbox/atlas
> Add Atlas Server to product menu

- CHANGELOG.md
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/page-layout.js
This includes two updates to the `PageLayout` component: 
1️⃣ Show scroll bar automatically (not just when scrolling) when the sidebar contents overflow vertically. 
2️⃣ Removes `activeClass="bg-gray-faint"` from the sticky sidebar to prevent this from happening when the `sidebarTheme` is set to something other than the default (`bg-gray-faint`):
> Update PageLayout component

- CHANGELOG.md
- src/components/card/__tests__/card-test-cases.js
- src/components/card/card.js
- src/components/level-indicator/__tests__/level-indicator-test-cases.js
- src/components/level-indicator/level-indicator.js
This PR does two things: 
1️⃣ Adds a new `LevelIndicator` component based on the work done in /help (ty @danswick). 
2️⃣ Adds optional `level` and `language` props to `Card` (to be used for /help tutorials).
Closes #53
> Add LevelIndicator component

- CHANGELOG.md
- src/data/product-menu-items.js
Adds a link to the new Mapbox China plugin for iOS docs in the `+ More` section.
> Add China plugin for iOS to product-meun-items file

- CHANGELOG.md
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/navigation-accordion.js
I want to be able to show third-level items in the API documentation. (It could also be useful to show third-level items in the Studio Manual.) @colleenmcginnis helped me update the NavigationAccordion component and update the tests file 🙇‍♀️
> Update NavigationAccordion to show level 3 headings

- CHANGELOG.md
- src/components/sectioned-navigation/__tests__/sectioned-navigation-test-cases.js
- src/components/sectioned-navigation/sectioned-navigation.js
Adds the option to add a filter bar that allows you to filter items listed. This attempts to recreate what is done in the Mapbox GL JS docs ([code](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/components/example.js#L87-L104) / [see it in action](https://www.mapbox.com/mapbox-gl-js/examples/)). 
@davidtheclark very open to suggestions if you have any.
> Add filter option to SectionedNavigation

- CHANGELOG.md
- src/components/back-to-top-button/back-to-top-button.js
- src/components/page-layout/page-layout.js
https://github.com/mapbox/dr-ui/commit/72b9f9abb9b5bd3c291b5528a12c473252e8507e fixes #61 
https://github.com/mapbox/dr-ui/commit/39eb8dc943eab1a4f381a898013b5ec13aaa492f fixes #57
> Little bug fixes

- CHANGELOG.md
- src/components/product-menu-dropdown/product-menu-dropdown.js
- src/data/product-menu-items.js
Prepares the docs product menu for https://github.com/mapbox/mapbox-gl-js/pull/7530. Adds Mapbox Style Specification to `src/data/product-menu-items.js` and adds an exception to `ProductDropdownMenu` to account for the page path for the Style Spec being in the /mapbox-gl-js repo.
> Add Mapbox style spec to product dropdown menu

- CHANGELOG.md
- src/components/examples-page/examples-page.js
I think we should remove the `pt60` class from `ExamplesPage` component. I'm noticing that it can add too much spacing between elements:
If a particular page requires more padding, then we should wrap it this component in a div with the desired classes.
> [ExamplesPage] remove pt60 class

- CHANGELOG.md
- src/components/card-container/card-container.js
- src/components/card/card.js
This PR makes a few subtle padding and style adjustments to `Card` and `CardContainer`. 
Right now each card has padding that is revealed when hovered by the addition of a shadow. Unfortunately, this adds unused padding to the design and knocks the cards out of alignment with each heading:
The changes in this PR, removes the padding around each card and changes the hover interactive to a changing the card's hover text color blue:
~~I'd also like to make the images have rounded corners, but I suspect I'll need to PR the ability to pass props in https://github.com/mapbox/appropriate-images~~ Nevermind! We can pass `style` to the element!
> [Card/CardContainer] styles updates

- README.md
This updates any www.mapbox.com/assembly link to the new labs subdomain link.
@mapbox/frontend-platform for review, please.
> Move to new labs subdomain

- CHANGELOG.md
- src/components/page-layout/page-layout.js
- src/css/docs-prose.css
I believe `NavigationDropdown` was being obfuscated by a parent with `.scroll-auto` and an absolutely positioned container. I created a new class `.scroll-auto-mm` as that class is only needed for larger screens. We will also need to make style adjustments in each repo's page-shell to remove the absolutely position classes (PR forthcoming in /help).
I also adjusted the padding around the content for mobile sizes as it was a bit too wide:
> ![img_f8cc152effdc-1](https://user-images.githubusercontent.com/2180540/50160648-dce06c00-02a7-11e9-954f-38f6dc3b61ad.jpeg)
> cleans up styles to allow `NavigationDropdown` to appear on iOS

- CHANGELOG.md
- src/components/back-to-top-button/back-to-top-button.js
fixes #76, by adding `window.scroll()` and keeping `document.documentElement.scrollTop` as a fallback since the former doesn't have complete browser support
> adds `window.scroll()` to `BackToTopButton`

- CHANGELOG.md
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/page-layout.js
The width of the sidebar and content is fixed in dr-ui's `PageLayout`. Sometimes our content asks for more flexibility. This PR adds an optional prop `sideBarColSize`, a number. If available, dr-ui will use that number for the sidebar column: `col--[sideBarColSize]-ml` and then compute the content column size: `col--[12 - sideBarColSize]-ml` size.
We'll keep the `-mm` col sizes as they are to make sure that content doesn't get too squished at that breakpoint.
For quality control, sideBarColSize must be > 2 and < 7. Otherwise it will ignore the value and use the default column sizing.
> [PageLayout] adds optional prop to change the column size of the sidebar

- CHANGELOG.md
- src/css/docs-prose.css
For each `#docs-content` rules, I added a child selector to give us more flexibility and avoid adding more than one `#doc-content` to a single page
fixes #85
> additional selectors for `#docs-content`

- CHANGELOG.md
- src/components/page-layout/page-layout.js
This content div adds padding:
From my testing, we don't need it!
@colleenmcginnis for review 🙇‍♀️
> [PageLayout] rm px12 on content

- CHANGELOG.md
- src/components/page-layout/page-layout.js
On the new mapbox-gl-js page, when you start expanding the api items, the length of the page changes. However, since we aren't listening for changes to the page height the sticky sidebar gets unmounted from its position too early: 
This PR adds an optional prop that you can pass a class that you want to watch for clicks. If that element is clicked then the height of the page will be recalculated and the sticky sidebar will adjust and stay mounted until the bottom of the page.
@colleenmcginnis for review 🙇‍♀️ this is a little tricky to test in our current testing suite
> [PageLayout] adds optional interactiveClass prop to watch for changes on click

- CHANGELOG.md
- src/components/topbar-sticker/__tests__/topbar-sticker-test-cases.js
- src/components/topbar-sticker/topbar-sticker.js
This optional prop for `TopbarSticker` will afford us a little wiggle room in customizing when the component should unstick itself. When the prop is not supplied, it will default to `640`.
> Add optional `unStickWidth` prop to `TopbarSticker`

- CHANGELOG.md
- src/components/overview-header/__tests__/overview-header-test-cases.js
- src/components/overview-header/overview-header.js
This PR adds a new optional prop `contactLink` to `OverviewHeader` which will add a "Contact us" button to the header if populated:
This PR also wraps the version in a code element to increase discoverability of the version number in the header.
> [OverviewHeader] Add `contactLink` to create Contact us button

- CHANGELOG.md
- src/components/book-image/book-image.js
- src/components/booklet-image/booklet-image.js
- src/components/contact-image/contact-image.js
- src/components/note/__tests__/note-test-cases.js
- src/components/note/note.js
- src/components/troubleshoot-image/troubleshoot-image.js
- src/components/warning-image/index.js
- src/components/warning-image/warning-image.js
@colleenmcginnis do you know offhand if we have any sites using the Note component and passing a custom theme to it? This PR proposes to remove passing style-based themes and replace it with keyword themes (default/no theme specified, warning, error). If it's important to be able to customize the note, I can adjust!
fixes #94
> Add warning and error themes to `Note`

- CHANGELOG.md
- src/components/sectioned-navigation/__tests__/sectioned-navigation-test-cases.js
- src/components/sectioned-navigation/sectioned-navigation.js
Refs https://github.com/mapbox/mapbox-gl-js/issues/7888
In the `SectionedNavigation` when `includeFilterBar` is true, if the dataset sent to the component includes a `description`, then we'll also filter on the description in addition to the title.
How to test: I updated the *With a title, linked section headings, counts, and filter*  test case on http://192.168.7.223:9966/SectionedNavigation with a few descriptions. You can try searching for `pizza` or `pretzels` (naturally).
> [SectionedNavigation] filter the description if it's available

- CHANGELOG.md
- package.json
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/css/docs-prose.css
- src/test-cases-app/index.html
When markdown parses code blocks, it adds classes with the language to the pre element, for example: `class="language-html"`.
This PR updates the `.prose pre` classes in docs-prose.css to only apply the classes if the pre element has a `language-` class.
This will keep example pages on our various docs sites from getting max-height on code blocks, where it's not preferred.
This PR also copies over docs-prose.css to the test-cases-app so we can see it in use!
How to test: to PageLayout I added a test case to simulate code output.
> [docs-prose.css] make `.prose pre` rules more specific

- CHANGELOG.md
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/navigation-accordion.js
Related: https://github.com/mapbox/android-docs/pull/842
Adds an additional prop to `NavigationAccordion` for adding a tag to a first level item.
> Add optional prop for tags for first level items in NavigationAccordion

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/beta-flag/__tests__/beta-flag-test-cases.js
- src/components/beta-flag/beta-flag.js
- src/components/beta-flag/index.js
- src/components/overview-header/__tests__/overview-header-test-cases.js
- src/components/overview-header/overview-header.js
- src/components/product-menu/__tests__/product-menu-test-cases.js
- src/components/product-menu/product-menu.js
This PR:
- Bumps the version of mr-ui to v0.7.0
- Adds `BetaFlag` component extending the mr-ui `Badge` component
- Adds `beta` prop to `OverviewHeader`
- Adds `beta` prop to `ProductMenu`
In practice, use of these components should look like this:
> Add BetaFlag component and options to add it to other components

- CHANGELOG.md
- src/components/card-container/card-container.js
- src/components/sectioned-navigation/sectioned-navigation.js
- src/components/topbar-sticker/topbar-sticker.js
Adds `data-swiftype-index="false"` to content that we don't necessarily want to get index.
The counter number in the card container title adds some cruft, so we should not index that number. Otherwise it could show up in results and looks out of place:
Turning off indexing for the sectioned navigation as a whole since all the content is duplicated in the body of the page.
refs https://github.com/mapbox/documentation/issues/76#issuecomment-480016159
> add swiftype attribute to ignore content blocks

- CHANGELOG.md
- src/components/back-to-top-button/back-to-top-button.js
fixes #120 
Firefox: 
Chrome:
Safari:
> fixes bug in firefox where arrow was not vertically centered

- CHANGELOG.md
- src/components/card/card.js
I forgot to wrap LevelIndicator in txt-s txt-bold as it appears in the Card component:
> [card] wrap LevelIndicator in txt-s txt-bold

- CHANGELOG.md
- src/components/search/search-box.js
This PR will open the search results when the input is focused if a search query was exists in a URL parameter.
How to test:
1. run `npm start`
2. visit http://192.168.7.223:9966/Search?q=styles&size=n_10_n
3. Click or tab to the search box, the result box should open with results for the query found in the URL.
> [search] open the menu onFocus

- CHANGELOG.md
- src/helpers/mapbox-tileset-style-json.js
🐌 _non-urgent_
We're using the same style JSON for the minimal styles used in the [Vector tiles documentation](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/) and [How Mapbox works](https://docs.mapbox.com/help/how-mapbox-works/#use-mapbox-map-data). This PR adds the style JSON here so we only have to maintain it in one place. 
@katydecorah I added this to the `/helpers` folder, but feel free to suggest a different way to organize this if you have any ideas!
> Add style JSON for styles illustrating Mapbox-maintained tilesets

- CHANGELOG.md
- src/components/search/search-result.js
- src/helpers/title-generator.js
- tests/title-generator.test.js
This PR adds a new function `titleGenerator` that takes a page's title, subsite (if available), and site and outputs an array for the meta `<title/>` tag (in docs-page-shell) and the title for each search result.
We make a few transformations to:
* Remove duplicates in the title tag.
* Remove "Introduction" from title and skip right to subsite or site name.
* Remove redundancy in subsite names by removing the "...for (product)". 
For pages titled "Introduction" we skip right to the subsite or site name. This simplifies the result:
--------|----------
This PR also asserts the new function through tests.
> [helper function] title generator

- CHANGELOG.md
- src/components/search/search-box.js
This PR sets `debounce` to 300 to help prevent
e
ev
eve
ever
every 
every l
every le
every let
every lett
every lette
every letter 
every letter f
every letter fr
every letter fro
every letter from 
every letter from b
every letter from be
every letter from bei
every letter from bein
every letter from being
every letter from being s
every letter from being se
every letter from being sear
every letter from being searc
every letter from being search
every letter from being searche
every letter from being searched
> "debounce" search requests to avoid creating an excessive number of requests. This controls the length to debounce / wait.
As a result it will take an extra second for results to display, but I think the pay off of preventing unnecessary requests is worth it.
> [search] debounce search results

- CHANGELOG.md
- src/components/page-layout/page-layout.js
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/components/topbar-sticker/topbar-sticker.js
While reviewing https://github.com/mapbox/studio-manual/pull/73 I noticed that the sticky sidebar has a zIndex fight with the illustrations.
We updated the zIndex for the TopBarSticker to 3 in https://github.com/mapbox/dr-ui/pull/67 and I think we should do the same for the sidebar sticky navigation.
> increase zIndex for sticky sidebar

- CHANGELOG.md
- src/components/search/search-modal.js
> increase modal zindex to prevent collision with topbar sticker

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/components/search/__tests__/search-test-cases.js
- src/components/search/__tests__/search.test.js
- src/components/search/search-box.js
- src/components/search/search.js
If you set the `site` prop, it will add a toggle at the top of the results so that the user can filter results for the current site or across all docs.
Unfortunately, we cannot default the toggle to the current site (waiting for sticky filters upstream in search-ui). Without sticky filters, any filter we set manually gets reset when the user searches. Hopefully we'll be able to add this in the near future.
> ![image](https://user-images.githubusercontent.com/2180540/58805893-fb7eb900-85e2-11e9-85ba-e2a901d088e4.png)
> ![image](https://user-images.githubusercontent.com/2180540/58805909-076a7b00-85e3-11e9-8b9d-de0757c16aa6.png)
How to test:
1. npm run start
2. Navigate to http://192.168.7.223:9966/Search
3. Try the second test case: "Basic search with `site` set to show filter toggle"
> [search] add ability to filter results to current site versus all docs

- CHANGELOG.md
- package-lock.json
- package.json
- src/.eslintrc.json
- src/components/search/search-box.js
- src/test-cases-app/test-cases-app.js
This PR adds tracking to our Search component for:
1. Queries typed
2. Result clicked
How to test:
1. npm install
2. npm start
3. open segment > sources > mapbox-staging (leave window open) 
4. in another window: navigate to http://192.168.7.223:9966/Search
5. type a query, click a result
6. switch back to segment and click "Pause" and search for "Searched docs" events. Click each one. You should see an event for the queries and an event for the clicked item:
When you click "Raw" you'll see the metadata attached with the event, including page searched from 🎉
> [search] adds segment tracking for queries and clicks

- CHANGELOG.md
- scripts/build-package.js
When we run `npm run build` a script does a lot of things to get dr-ui ready for npm. This PR removes our optionalDependencies from being included in the npm version of our package.json.
While updating dr-ui on /mapbox-gl-js, I ran into an issue where yarn said:
```
error Couldn't find package "@mapbox/web-analytics@^0.5.1" required by "@mapbox/dr-ui@0.15.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Since we're already removing devDependencies from package.json for the npm version, I think it's safe to also remove optionalDependencies.
We can also remove `jest` from package.json since that's only needed for development.
---
How to test:
1. pull down branch
2. run `npm run build`
3. open `pkg/package.json`
4. you should …
> 🐛do not package optionalDependencies

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/search/search-box.js
- src/components/search/search-result.js
- src/components/search/search.js
This PR:
* updates the search-ui component to 0.10.0
* adds a spinning loader while the search engine is loading results
* increase to the debounce length to help prevent fragmented queries
* reset search when modal is closed
> update search-ui, add loader, increase debounce length

- CHANGELOG.md
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/page-layout.js
- src/components/search/__tests__/__snapshots__/search.test.js.snap
Similar to #119 adding the data attribute to the `PageLayout` sidebar to help improve search results.
🐌
> [PageLayout] add data attribute to prevent Swiftype from indexing sidebar content

- CHANGELOG.md
- src/helpers/version-sort.js
- tests/version-sort.test.js
Tested locally in /ios-sdk:
Removed the latest stable and pre-releases appear:
Refs https://github.com/mapbox/ios-sdk/issues/729
> [version-sort] do not push pre-releases of the latest stable version

- CHANGELOG.md
- src/components/search/search-box.js
Adds missing proptype to search-box.js which is causing #144 to fail. 🐌
> [search] adds missing proptype

- src/components/search/search.js
This will fail on npm run build if we do not check if window and document are defined before evaluating.
Presently testing package locally and testing with `npm run build`
> [search] make sure window and document are defined before evaluating

- CHANGELOG.md
- src/components/new-image/_tests_/__snapshots__/new-image.test.js.snap
- src/components/new-image/_tests_/new-image-test-cases.js
- src/components/new-image/_tests_/new-image.test.js
- src/components/new-image/index.js
- src/components/new-image/new-image.js
- src/components/note/__tests__/note-test-cases.js
- src/components/note/note.js
@brsbl noted in our update of the Tilesets API docs that:
> we usually use orange to denote things like deprecation/bad things and I wonder if a different color signifying a good thing (light green?) might make more sense?
This makes sense to me! This PR creates a new Note flavor to indicate that _a product or feature is new_.  
@mapbox/docs to review, please 🙏
> Create a note "flavor" for new products or features

- CHANGELOG.md
- src/components/back-to-top-button/__tests__/back-to-top-button-test-cases.js
- src/components/back-to-top-button/back-to-top-button.js
Found this bug in Sentry related to the BackToTop button, where a slight change in syntax will give us better browser coverage:
* `window.scroll(x-coord, y-coord)` works in most browsers
* `window.scroll(options)` does not work in most browser
Ref https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll#Browser_Compatibility
Ref https://sentry.io/organizations/mapboxcom/issues/929306724/
🐌 no rush in review 🐌
> [BackToTop] use `window.scroll(x-coord, y-coord)` 

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/search/search.js
While reviewing Sentry errors, I noticed that the search component is throwing errors in older browser versions like Firefox 44. 
* Adding [babel's poyfill](https://babeljs.io/docs/en/babel-polyfill) to the search component fixes this issue with older browsers versions (just not IE11 because it's out of scope for the search library).
* Ref: https://sentry.io/organizations/mapboxcom/issues/1131166287/?referrer=slack
I built this PR locally and tested on /geographic-analytics:
You can test this PR by:
1. npm install
1. npm run build
1. Opening another repo to test locally, like geographic-analytics, and replacing the dr-ui version number in package.json with the path to your local dr-ui repo: `"@mapbox/dr-ui": "file:/Users/katydecorah/Documents/GitHub/dr-ui/pkg",`
1. run npm install (you …
> [search] polyfill search component to catch errors

- CHANGELOG.md
- package-lock.json
- package.json
- src/.eslintrc.json
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/demo-iframe/__tests__/demo-iframe-test-cases.js
- src/components/demo-iframe/__tests__/demo-iframe.test.js
- src/components/demo-iframe/demo-iframe.js
- src/components/demo-iframe/index.js
- src/components/gl-wrapper/__tests__/__snapshots__/gl-wrapper.test.js.snap
- src/components/gl-wrapper/__tests__/gl-wrapper-test-cases.js
- src/components/gl-wrapper/__tests__/gl-wrapper.test.js
- src/components/gl-wrapper/gl-wrapper.js
- src/components/gl-wrapper/index.js
This component is a wrapper where we can pass HTML/Component to it as a prop. The wrapper will decide if the browser supports webgl. If it does then it'll show whatever code you passed to it, if it doesn't then it'll display a note with a warning.
Refs https://github.com/mapbox/documentation/issues/236
WebGL supported:
WebGL unsupported:
How to test:
1. npm install
2. npm start
3. Open the component in a browser you know to have GL support (your regular browser) you should see a typing cat.
4. Open the component in a browser that doesn't support GL or disable GL support. Here's how you can disable GL in Firefox:
- Open the browser settings page. To do this, type in the address bar: about:config.
- In the search box, type in: webgl.
- Find line “webgl.disabled”. It has the “false” value. …
> Create GL Support wrapper

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/syntax-highlighting/__tests__/__snapshots__/syntax-highlighting.test.js.snap
- src/components/syntax-highlighting/__tests__/syntax-highlighting-test-cases.js
- src/components/syntax-highlighting/__tests__/syntax-highlighting.test.js
- src/helpers/highlight-html.js
- src/helpers/highlight-java.js
- src/helpers/highlight-json.js
- src/helpers/highlight-jsx.js
- src/helpers/highlight-objectivec.js
- src/helpers/highlight-swift.js
- src/helpers/highlight-xml.js
After reviewing https://github.com/mapbox/android-docs/pull/1037 I realized there were several other docs sites using this pattern. This PR pulls them all together in a central place and adds the same check as in https://github.com/mapbox/android-docs/pull/1037 to each to avoid errors.
@katydecorah I wasn't sure how to test these. I wanted to have something visual so I could confirm that the highlighting looked right. I made a new folder in `src/components/` that only had a `__tests__` folder (no js file with a component) so I could visually test. I feel like this is `wrong` but I think that the build script ignores the `__tests__` folder so maybe it's ok? Let me know what you think!
> Add syntax highlighting functions

- README.md
- package.json
- scripts/rm-search.js
- src/test-cases-app/test-cases-app.js
Fixes #170
This PR adds a new script `npm run start-legacy` so that we can run the test-cases app in IE11. It's a little hacky (it uses the same script for npm run start, but removes the Search module so it doesn't get built), but I think it gets the jobs done and makes it easier for us to test.
🐌
> create `npm run start-legacy` to test in IE11

- CHANGELOG.md
- src/components/feedback/feedback.js
This PR adds:
* `environment`: staging or production. This uses the same logic that we use to determine which webhook to send the request to.
* `location`: this provides the `window.location` object for full details on the current page.
To test:
1. npm start
2. navigate to http://192.168.7.223:9966/Feedback
3. check #bots for the response
The payload should look like:
```json
{
"event": "Sent docs feedback",
"properties": {
"helpful": true,
"site": "Help",
"browser": "chrome",
"browserVersion": "76.0.3809",
"os": "Mac OS",
"page": {},
"preferredLanguage": "Swift",
"environment": "staging",
"location": {
"href": "http://192.168.7.223:9966/Feedback",
"ancestorOrigins": {},
"origin": "http://192.168.7.223:9966",
"protocol": "http:",
"host": "192.168.7.223:9966",
"hostname": "192.168.7.223", …
```
> [Feedback] send `environment` and `location` with feedback

- CHANGELOG.md
- src/components/video/__tests__/__snapshots__/video.test.js.snap
- src/components/video/__tests__/video-test-cases.js
- src/components/video/video.js
When rolling out v0.21.1 to all repos, I came across a build error related to the Video component (catching on [this use of `window`](https://github.com/mapbox/dr-ui/blob/master/src/components/video/video.js#L10-L13)). I did two things in this PR to address it:
- Use /mr-ui's `getWindow` (for consistency).
- Check for the `window` within `componentDidMount` (this seems to be the important part).
- I chose to store the videoProps (which depend on the results the part that uses `getWindow`) in `state` because that seemed to be a pattern used in mr-ui components that use `getWindow`. Up for other suggestions, though! 
I tested this by building and installing this locally in /ios-sdk and /android-docs. I was able to build both sites successfully and the resulting static site worked as …
> Fix Video build

- CHANGELOG.md
- src/components/feedback/feedback.js
per https://github.com/mapbox/dr-ui/pull/186#issuecomment-531808947 this PR removes the get-window function from feedback to prevent throwing errors when we'd prefer it to fail silently
Response in #bots:
```
{
"event": "Sent docs feedback",
"properties": {
"helpful": true,
"site": "Help",
"browser": "chrome",
"browserVersion": "76.0.3809",
"os": "Mac OS",
"page": {},
"preferredLanguage": "Swift",
"environment": "staging",
"location": {
"href": "http://192.168.7.223:9966/Feedback",
"ancestorOrigins": {},
"origin": "http://192.168.7.223:9966",
"protocol": "http:",
"host": "192.168.7.223:9966",
"hostname": "192.168.7.223",
"port": "9966",
"pathname": "/Feedback",
"search": "",
"hash": ""
}
},
"anonymousId": "...."
}
```
> [Feedback] remove get-window

- CHANGELOG.md
- src/components/glossary-card/__tests__/__snapshots__/glossary-card.test.js.snap
- src/components/glossary-card/__tests__/glossary-card-test-cases.js
- src/components/glossary-card/__tests__/glossary-card.test.js
- src/components/glossary-card/glossary-card.js
- src/components/glossary-page/__tests__/__snapshots__/glossary-page.test.js.snap
- src/components/glossary-page/__tests__/glossary-page-test-cases.js
- src/components/glossary-page/__tests__/glossary-page.test.js
- src/components/glossary-page/glossary-page.js
- src/components/glossary-section/__tests__/__snapshots__/glossary-section.test.js.snap
- src/components/glossary-section/__tests__/glossary-section-test-cases.js
- src/components/glossary-section/__tests__/glossary-section.test.js
- src/components/glossary-section/glossary-section.js
Adds three components for building pages with an alphabetized list of terms (currently used to build the [Glossary page](https://docs.mapbox.com/help/glossary/)):
**`GlossaryCard`** for a single term.
**`GlossarySection`** for defining the layout for each letter including the letter and `GlossaryCard`s for relevant cards.
**`GlossaryPage`** for defining the layout for all `GlossarySection`s.
> Add glossary components

- CHANGELOG.md
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/components/search/__tests__/search-test-cases.js
- src/components/search/search-box.js
This PR can be reviewed when we're ready to make the next release.
This PR updates the theme for the Search button:
* Uses Assembly `btn` classes for consistency
* Makes button a little more prominent, without drawing too much attention
* Uses accessible colors (current contrast ratio is too low)
Status | Image
--- | ----
Before | ![image](https://user-images.githubusercontent.com/2180540/65343640-76c0a680-dba3-11e9-96a6-9c7e23c85ac3.png)
After | ![image](https://user-images.githubusercontent.com/2180540/65343623-69a3b780-dba3-11e9-9a3f-11ec25283a85.png)
Status | Image
--- | ----
Before | ![image](https://user-images.githubusercontent.com/2180540/65343724-b38c9d80-dba3-11e9-90aa-8f45126a7a28.png)
After | ![image](https://user-images.githubusercontent.com/2180540/65343710-a2439100-dba3-11e9 …
> new theme for search button

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- scripts/rm-search.js
- src/components/search/search.js
- src/test-cases-app/test-cases-app.js
search-ui@1.3.0 released yesterday along with better support for IE11! 
Search will work in IE11 🎉 🎉 
* along with the update, we can remove the `babelInclude: ['mimic-fn', 'debounce-fn’],` line from every batfish config (search-ui's latest update gets rid of those dependencies so we no longer need to have babel take care of them).
* removed core-js and runtime-regenerator as polyfills, because they were not doing the necessary polyfill-ing. 
- I tried playing around with the polyfill's settings: I know that we needed to polyfill `entries`, `startsWith`, and `Promise` then after that it stopped giving error message and the search loading would just spin without loading results.
- After seeing this thread https://github.com/elastic/search-ui/issues/437#issuecomment-565642673 I tried using …
> Support for Search in IE11 🎉

- CHANGELOG.md
- src/components/beta-flag/__tests__/__snapshots__/beta-flag.test.js.snap
- src/components/beta-flag/beta-flag.js
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
Updates the style of the `BetaFlag` component to:
- Match the color of the `Note` component's `new` theme.
- Increase the contrast when used with the `NavigationAccordion` component.
> Update style of BetaFlag

- CHANGELOG.md
- src/components/beta-flag/__tests__/__snapshots__/beta-flag.test.js.snap
- src/components/beta-flag/beta-flag.js
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/__tests__/navigation-accordion.test.js
- src/components/navigation-accordion/navigation-accordion.js
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/search/__tests__/__snapshots__/search.test.js.snap
Adds an optional `tag` prop to `secondLevelHeadings` and `thirdLevelHeadings` in `NavigationAccordion`.
> Add "tag" option to second and third level headings

- src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap
- src/components/related-page/related-page.js
@colleenmcginnis Since the new RelatedPage component is based off of Note, I wanted to make sure the patterns were introducing in #202 also come through here. I hope you don't mind that I created this PR/fork off of #213 🙏 
* Create a defaultProp for `contentType` (similar to what will be added in #202).
* Made light adjustments to spacing.
* Add `a11yColor` for when the dark theme color doesn't have a high enough contrast.
* Make the border a little thicker around the component.
* A couple mobile styles to hide the image on small screens.
Let me know what you think!
> design suggestions for RelatedPage

- CHANGELOG.md
- src/css/docs-prose.css
Fixes https://github.com/mapbox/dr-ui/issues/221. 
We generally use anchor elements as children of H2 and H3 components, so this rule isn't necessary and can inadvertently created large clickable areas in the whitespace surrounding heading text.
> Remove cursor:pointer from docs-prose h2's and h3's

- CHANGELOG.md
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/gl-wrapper/__tests__/__snapshots__/gl-wrapper.test.js.snap
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/note/__tests__/__snapshots__/note.test.js.snap
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/tag/__tests__/__snapshots__/tag.test.js.snap
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/themes.js
@colleenmcginnis While testing the latest dr-ui release on /api, one beta note is particularly large and I think that the bright blue text color was a little jarring and not as easy to read as the surrounding text (despite being AA compliant!). This PR darkens the text color on the default, warning, beta, new, and download themes.
---|---
> Darken text color on default, warning, beta, new, and download themes to improve readability

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/code-snippet/__tests__/__snapshots__/code-snippet.test.js.snap
- src/components/edit/__tests__/__snapshots__/edit.test.js.snap
- src/components/edit/edit.js
We're using prettier in the browser to format the code for the Edit buttons. Unfortunately Prettier uses `startsWith` which is not compatible with IE11. This PR replaces Prettier with Indent.js which doesn't exactly what we need and works on IE 11.
Note: this code indentation/beautifying feature is purely cosmetic to make the code look nice when you export it. If we have any more problems with it (I don't think we will) we can scrap indenting the code.
> replace prettier (browser) with indent.js in Edit component

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/code-snippet/__tests__/__snapshots__/code-snippet.test.js.snap
- src/components/edit/__tests__/__snapshots__/edit.test.js.snap
- src/components/edit/__tests__/edit-test-cases.js
- src/components/edit/edit.js
#226 was a bust. Once dr-ui is compiled, indent.js didn't have default exports for each function and broke on production. Since code formatting the exported code is purely cosmetic, I feel ok with removing it completely.
> remove code formatting from Edit component

- CHANGELOG.md
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/gl-wrapper/__tests__/__snapshots__/gl-wrapper.test.js.snap
- src/components/note/__tests__/__snapshots__/note.test.js.snap
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/themes.js
> use number for icon `size` to prevent small icons in firefox

- CHANGELOG.md
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/feedback/__tests__/feedback-test-cases.js
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/navigation-accordion/navigation-accordion.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/page-layout.js
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/components/search/__tests__/search-test-cases.js
- src/components/sectioned-navigation/__tests__/__snapshots__/sectioned-navigation.test.js.snap
- src/components/sectioned-navigation/sectioned-navigation.js
This PR makes sure all sidebar items are lined up:
* Fixes uneven side spacing on NavigationAccordion, fixes #253 
* Adds the same padding to sidebarTitle in PageLayout
* Give SectionedAccordion same spacing
---|---
1. `npm start`
2. Navigate to /NavigationAccordion, /SectionedNavigation; /Feedback as a nice PageLayout example that you can preview
I also copied this component as a test in /mapbox-gl-js-docs:
1. Open /mapbox-gl-js-docs locally, pull down the `nav-accordion-test` branch.
2. `yarn install`
3. `yarn start`
4.  Visit every /overview, /api, /examples to make sure all sidebar items are lined up.
- SectionedNavigation - 90
- PageLayout - 90
- NavigationAccordion - 91
> Make NavigationAccordion, SectionedAccordion, and PageLayout>sidebarTitle line up

- CHANGELOG.md
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/__tests__/navigation-accordion.test.js
- src/components/navigation-accordion/navigation-accordion.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/test-cases-app/index.html
This PR:
* adds an `icon` option for third level items. This option accepts a maki icon value.
* added test-case only css to set the max-width of NavigationAccordion to 400px (which is the max-width the component usually sees on the page) - this will help catch layout issues a little better.
Fixes #235
> ![image](https://user-images.githubusercontent.com/2180540/74482288-3a5b5300-4e82-11ea-8c5d-0ffeb8ec287b.png)
1. `npm start`
2. Navigate to /NavigationAccordion
3. Test `Shows third level items with icons` test case.
I also copied this component as a test in /mapbox-gl-js-docs:
1. Open /mapbox-gl-js-docs locally, pull down the `nav-accordion-test` branch.
2. `yarn install`
3. `yarn start`
4.  Visit /mapbox-gl-js/style-spec/layers/#fill-extrusion to check the icons on the layer's page.
- …
> Add `icon` option for third level items in NavigationAccordion

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/feedback/__tests__/__snapshots__/feedback-sent-rating.test.js.snap
- src/components/feedback/__tests__/__snapshots__/feedback-sent-text.test.js.snap
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/feedback/__tests__/feedback-sent-rating.test.js
- src/components/feedback/__tests__/feedback-sent-text.test.js
- src/components/feedback/feedback.js
- src/components/feedback/forward-event.js
This PR:
- adds tests to assert the object shape for events sent to Segment.
- pushes the Segment event to the state for easier testing/tracking.
- adds createId function to generated a unique id for each interactive element.
- reorganizes functions and adds comments to help make all the actions clear.
I think this PR will help us better track additions to metadata (like in #255).
1. `npm start`
2. Open /Feedback
3. Try any test case, you can see the Segment event posted in #bots and the Sentry feedback posted in #docs-feedback.
- Score is 89 due to: 
- #257 color contrast 
- [id] attributes on the page are not unique (#docs-content is baked into test cases)
- #248 form elements missing label
> Add tests to assert Segment event in Feedback component

- CHANGELOG.md
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/feedback/__tests__/feedback-sent-rating.test.js
- src/components/feedback/__tests__/feedback-sent-text.test.js
- src/components/feedback/__tests__/feedback-test-cases.js
- src/components/feedback/feedback.js
This PR:
- Replaces the Feedback component's `userName` prop with the `user` object (which we will populate using a docs-page-shell function)
- Sends `plan` information to Segment 
- Sends user data (username, plan, email) to Sentry
- Adds line comments
To do:
1. `npm start` and open /Feedback test case app OR test the /api-documentation branch `dr-ui-0.27.0` locally
2. You should check the response in two places:
- #bots (Segment) 
- [docs-feedback Sentry project](https://sentry.io/organizations/mapboxcom/issues/?environment=staging&project=1848287&referrer=slack)
On the /api-documentation branch, try sending feedback signed in and signed out. Look for:
- signed in - Your userId and plan are found in the #bots event object. Your userId and email are found in the "User" section of the …
> Send basic user metadata along with Feedback

- CHANGELOG.md
- src/components/contextless-android-activity-toggle/__tests__/__snapshots__/contextless-android-activity-toggle.test.js.snap
- src/components/contextless-android-activity-toggle/__tests__/contextless-android-activity-toggle-test-cases.js
- src/components/contextless-android-activity-toggle/__tests__/contextless-android-activity-toggle.test.js
- src/components/contextless-android-activity-toggle/__tests__/find-selected-code.test.js
- src/components/contextless-android-activity-toggle/contextless-android-activity-toggle.js
In the past, all Android docs had _at least_ Java code snippets and examples so we required the `java` prop in `ContextlessAndroidActivityToggle`. In most future releases, all Android docs will have Kotlin snippets (and will likely _not_ have Java snippets). 
A copy of this component is used on the `cmcg-adding-nav-1.0-examples` branch in /android-docs.
> Allow Kotlin-only activities

- CHANGELOG.md
- src/components/feedback/__tests__/feedback-test-cases.js
- src/components/search/__tests__/search-test-cases.js
- src/components/topbar-sticker/__tests__/topbar-sticker-test-cases.js
- src/components/topbar/__tests__/topbar-test-cases.js
- src/components/topbar/topbar.js
In https://github.com/mapbox/dr-ui/pull/274, I added `<div className="limiter">` to the new `Topbar` component in an effort to reduce code in individual repos. I think this was an over eager misstep, as it would require us to make a manual update to every page-shell to remove the now duplicated `<div className="limiter">`.
This PR reverts that change to prevent having to make lots of small updates in each repo.
> Remove `limiter` from Topbar

- CHANGELOG.md
- package-lock.json
- package.json
This PR pins the search-ui versions to prevent installs from choosing a later version (1.4.0 appends params to the URL even when the users is not searching, which we don't want.)
> Pin search-ui versions

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/feedback/__tests__/__snapshots__/feedback.test.js.snap
- src/components/feedback/__tests__/feedback-sent-rating.test.js
- src/components/feedback/__tests__/feedback-sent-text.test.js
- src/components/feedback/__tests__/feedback-test-cases.js
- src/components/feedback/examples/basic.js
- src/components/feedback/feedback.js
With the new layouts, it can be difficult to properly pass the user to the feedback component. This PR adds the call to MapboxPageShell to fetch the user inside the component.
> [layouts] Get user obj from inside feedback component

- src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap
- src/components/card-container/card-container.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/example-index.js
This PR makes a few small improvements to filters:
- Reverts the `cardColSize` for `CardContainer` back to `6`. During testing, cards with higher text density (such as Help tutorials) feel too crowded at size `4`. (This value was increased in #345 expecting the extra width in PageLayout would allow size `4` to fit better, but it did not.)
- Fixes logic for `showFilters` (if only one filter was chosen it would hide the filter completely, now it checks that the array has more than 0 items).
- Adds `grid` classes to filters, on smaller screens the filters will display in columns to take up more horizontal space:
Image | Image
---|---
- Preview http://localhost:8080/dr-ui/examples/ (`npm run start-docs`)
- Score is 98% due to #348 
> [info arch] Filter improvements

- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/examples/basic.js
- src/components/navigation-accordion/navigation-accordion.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/examples/example-page.js
- src/components/page-layout/examples/example.js
- src/components/page-layout/examples/full.js
- src/components/page-layout/examples/page.js
- src/helpers/batfish/__tests__/__snapshots__/navigation.test.js.snap
- src/helpers/batfish/__tests__/navigation.test.js
- src/helpers/batfish/navigation.js
This PR makes a proposal on how to handle the NavigationAccordion items on smaller devices ref https://github.com/mapbox/dr-ui/pull/344#issuecomment-721859813 and if accepted will merge into #344. This PR makes NavigationAccordion sub page menu's toggleable and will collapse the items on smaller devices be default:
- Separates the title/link and the chevron icon. The chevron icon is now a button that controls the sub page menu. The user can toggle a section's sub page menu from any page. 
- A section's sub page menu opens automatically when the section or any of its sub pages are active. However, on smaller devices all toggles are collapsed on load, but the user can toggle to reveal the subpages.
- On smaller devices, the padding for the NavigationAccordion links increases slightly to …
> [info arch] Make NavigationAccordion toggleable

- CHANGELOG.md
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- src/components/page-layout/layout.config.js
This is a small PR that addresses long horizontal text in the examples layout: 
- Adds an aside to the examples layout (or, really, un-hides it).
- Removes the bottom feedback from the examples page to avoid duplication.
- Pull down this branch
- `npm run start-docs` to view locally.
> [Info arch] Add aside with feedback to examples page layout

- CHANGELOG.md
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/examples/full.js
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/product-menu/product-menu.js
- src/components/tag/__tests__/__snapshots__/tag.test.js.snap
- src/components/tag/__tests__/tag-test-cases.js
- src/components/tag/__tests__/tag.test.js
- src/components/tag/examples/small.js
- src/components/tag/tag.js
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/__tests__/themes-test-cases.js
- src/components/themes/examples/basic.js
- src/components/topbar-sticker/__tests__/__snapshots__/topbar-sticker.test.js.snap
- src/components/topbar/__tests__/__snapshots__/topbar.test.js.snap
This PR solves an issue where the `Tag` in `ProductMenu` causes the title to be too truncated:
- Move the Tag above the title in `ProductMenu`
- Add new `small` prop/variant to `Tag` that condenses the tag and removes the border. **Is `small` a good prop name? Suggestions welcome!**
- Removes truncation from `ProductMenu`. We truncated this component to keep the ProductMenu content on one line because it lived in the TopbarSticker, but now the ProductMenu has lots of room to flow below.
---|---
- Try out the /PageLayout "full" test case (`npm start`)
- Try out the the /ProductMenu test cases (`npm start`)
> [info arch] Rework Tag in ProductMenu

- CHANGELOG.md
- docs/src/pages/components/index.md
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/overview-header/__tests__/overview-header-test-cases.js
- src/components/overview-header/examples/custom.js
- src/components/overview-header/overview-header.js
- src/components/page-layout/components/content.js
- src/helpers/batfish/__tests__/fixtures/data.json
This PR adds theming options to `OverviewHeader`:
- Adds `theme` prop that accepts CSS classes (usually an assembly background class).
- Adds `lightText` prop, when `true` the text color of the component will switch to white.
- Adds `description` prop to display a text description for the page.
- Makes `features` prop optional.
- In `PageLayout`, if `overviewHeader` is defined, then the title of the page (h1) will automatically not show. Previously, you had to set `hideTitle: true` in the page's frontMatter to prevent double headings from appearing.
- Observe the catalog page home page: /dr-ui/components/
- Observe the Overview header test cases page
> [info arch] Add theming options to `OverviewHeader`

- src/helpers/batfish/__tests__/filters.test.js
- src/helpers/batfish/__tests__/fixtures/gl-js-debug.json
- src/helpers/batfish/filters.js
In attempting to test Mapbox GL JS, I received the error:
```
TypeError: Cannot read property 'localeCompare' of undefined
```
There are several redirect pages in Mapbox GL JS example folder and the Batfish filter function was attempting to include them in building the filters. Since redirects do not have title, it failed while attempting to sort.
This PR filters out all pages that do not have a title to prevent pages without the correct amount of context from being included in the filter.
I created a reduced test case by carrying over three pages from Mapbox GL JS (the Examples index page, an examples redirect, and an examples page). I created a test to make sure that when filters are built with that dataset that no errors are thrown.
> [info arch] Filter out pages in filter helper that have no title

- src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.js.snap
- src/components/breadcrumb/breadcrumb.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/__tests__/page-layout.test.js
- src/components/page-layout/page-layout.js
This PR makes some updates to the Breadcrumbs component and how PageLayout displays the Breadcrumb component:
- On mobile, Breadcrumbs will display the second to last link with a back arrow. (Ignore the dotted border, that's from the test cases app).
Device size | Image
---|---
Large | ![image](https://user-images.githubusercontent.com/2180540/98958427-425b2880-24d0-11eb-9b04-52015fcff427.png)
Small | ![image](https://user-images.githubusercontent.com/2180540/98958388-38392a00-24d0-11eb-8970-41b8ecd128a6.png)
- While testing, I noticed that Breadcrumbs should only be shown on mobile if there is no sidebar. Otherwise the breadcrumbs site underneath the navigation and is redundant. This PR will make it so that the Breadcrumb component in PageLayout will only display on mobile if there is no …
> [info arch] Update Breadcrumbs on mobile

- CHANGELOG.md
- docs/src/pages/examples/index.md
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- src/components/page-layout/components/example-index.js
This PR allows contributors to place normal jsxtreme content in their examples index files. That content will be rendered above the examples content.
Check out the examples index in this repo's docs site!
> [Info arch] Allow children to appear at the top of example index pages

- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/card/__tests__/card-test-cases.js
- src/components/card/__tests__/card.test.js
- src/components/card/card.js
- src/components/card/examples/no-description.js
For info-arch rollout, we need to display some cards without descriptions. In order for prop validation to pass, the `description` prop needs to be optional.
> [Info arch] Make Card description optional

- src/components/page-layout/__tests__/page-layout-test-cases.js
- src/components/page-layout/components/example-index.js
- src/components/page-layout/page-layout.js
This PR fixes an issue where on some pages where `showFilters` is defined in the frontmatter and those filters do not have more than one option, the "Filters" heading appears:
> ![image](https://user-images.githubusercontent.com/2180540/99436786-7d4dc980-28df-11eb-8035-9900d2d216be.png)
This PR cleans up the evaluation of each filter and then will remove an item from `showFilters` if it does not have more than one option. Also, fixes PropTypes `showFilter` as it was formatted incorrectly.
Observe /PageLayout test case (`Example page layout, does not show filters because "showFilters" sets only "topics" and "topics" has one option.`)
> [info arch] Improve filter and showFilters handling

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/page-layout.js
This PR fixes the padding on the Breadcrumb component in PageLayout to better align with ProductMenu:
Stage | Image
---|---
Current |![image](https://user-images.githubusercontent.com/2180540/99431977-889df680-28d9-11eb-899c-791c7bcf80a0.png)
Proposed | ![image](https://user-images.githubusercontent.com/2180540/99431922-76bc5380-28d9-11eb-9b53-9c431ab2f857.png)
Visit /PageLayout test cases to make sure ProductMenu and Breadcrumb are aligned.
> [info arch] Fix Breadcrumb padding

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/examples/full.js
- src/components/page-layout/page-layout.js
This PR adds a new `domain` prop to PageShell. The props accepts an object with `title` and `path` to allow you to customize the first item in the breadcrumb. This PR also removes unused search-related props.
The "full layout" PageLayout test cases is now using the `domain` prop.
> [info arch] Add "domain" prop to PageShell; remove old search-related props

- src/css/docs-prose.css
This PR overrides `.limiter--wide` width at the 800px min-width query to fill the page's width more. This will help give the page layout more space on smaller devices.
Open the catalog page on a smaller monitor (1024 x 768). The `limiter-wide` class should have a width of `91.666666666%` (instead of `83.33333333%`)
> [info arch] Increase limiter--wide at 800px min-width query

- docs/batfish.config.js
- src/components/on-this-page/helpers.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/page-layout.js
- src/helpers/batfish/__tests__/fixtures/data.json
This PR;
- Replaces find with reduce (IE 11 does not support the find array method)
- Adds `width: 100%` to PageLayout `flex-child` elements to fix an IE 11 bug where content overflows.
- Fixes catalog site build in IE11 by adding `devBrowserslist: false,` to batfish.config.js
Run catalog site `npm run start-docs` on IE 11 without errors.
> [info arch] IE 11 fixes: replace find with reduce, fix flex-child

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/example-index.js
- src/components/page-layout/examples/example.js
This PR introduces a search to the filters in ExampleIndex that will allow the user to only display cards that have their text query in the title or description of the collection of cards.
> ![2020-11-18 at 4 24 PM](https://user-images.githubusercontent.com/2180540/99589925-abeca280-29ba-11eb-91eb-f6ebebe91e22.gif)
- Try out /PageLayout test case: `Example (index) layout.` 
- Try searching for different words in the title and the description of the cards, try lowercase and uppercase (search should be case insensitive).
- Do you have better naming suggestions for the label and placeholder? I'm not sure if I love it right now, but couldn't think of other ideas 🤔 
> [info arch] Add "search" filter to ExampleIndex

- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/overview-header/overview-header.js
This PR adds the `unprose` class to the OverviewHeader component's ul to allow us to better exclude this specific list from local list styles, Ref https://github.com/mapbox/studio-manual/pull/132
> [info arch] Add unprose class to OverviewHeader ul

- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/overview-header/overview-header.js
This PR will vertically center the content in OverviewHeader to keep the left-side content (heading, features, buttons, etc) in alignment with the right-side (image).
View the /OverviewHeader test case.
> [info arch] Add `flex-parent--center-cross` to OverviewHeader to center content

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/sidebar.js
- src/components/page-layout/page-layout.js
- src/components/search/__tests__/__snapshots__/search.test.js.snap
- src/components/search/search-box.js
- src/components/search/title-generator.js
- src/components/topbar-sticker/__tests__/__snapshots__/topbar-sticker.test.js.snap
- src/components/topbar/__tests__/__snapshots__/topbar.test.js.snap
- tests/title-generator.test.js
This PR adds back Search to the PageLayout component, by adding it to the sidebar under ProductMenu:
- Adds back `hideSearch` PageLayout prop to disable the feature for a given site (for example, /documentation, /jp)
- Updates the style of the Search button to complement the new layout
- Search component has the same behavior has before (show button that opens an input modal for larger screens and then on smaller screens replace button with input)
- Leaves titleGenerator intact (I mentioned removing it here, but to reduce scope I think we should leave Swiftype title tag alone for now in docs-page-shell -- I'll follow up in docs-page-shell while remove Swiftype from it.)
cc @danswick 
- Check the Search component in the /PageLayout and /Search test cases app pages
- Check the Search …
> [info arch] Add Search to PageLayout sidebar

- src/components/browser/__tests__/__snapshots__/browser.test.js.snap
- src/components/browser/__tests__/browser-test-cases.js
- src/components/browser/examples/basic.js
- src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap
- src/components/card-container/examples/basic.js
- src/components/card-container/examples/cols.js
- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/card/examples/basic.js
- src/components/card/examples/no-description.js
- src/components/demo-iframe/examples/basic.js
- src/components/phone/__tests__/__snapshots__/phone.test.js.snap
- src/components/phone/__tests__/phone-test-cases.js
- src/components/phone/examples/basic.js
- src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap
- src/components/related-page/examples/video.js
- src/components/video/__tests__/__snapshots__/video.test.js.snap
- src/components/video/__tests__/video-test-cases.js
- src/components/video/examples/basic.js
I noticed that some components on the catalog site have broken assets. This PR fixes the relative path to `files` so that the path will work for the test cases app and catalog page.
- The catalog page shouldn't log to console images or videos as 404.
- The test cases app assets load as expected: /Browser, /CardContainer, /Card, /DemoIframe, /Phone, /RelatedPage, /Video
> [info arch] Fix path to files to work for test cases app and catalog page

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/sidebar.js
This PR adds `h36` class to the div that wraps the Search component in PageLayout component. This will prevent the page from shifting while the search component loads.
This may be tricky to test effectiveness locally as I've only been able to reproduce on staging. But I think checking the /PageLayout tests cases app page to make sure the Search component loads as expected is a good thing to check.
@danswick for review
> [info arch] Set height to prevent content shift as Search component loads

- CHANGELOG.md
- src/helpers/batfish/__tests__/filters.test.js
- src/helpers/batfish/filters.js
This PR updates the filter Batfish helper to sort まず始めに (Getting started) to front of the topic list. 
- Review the new test (with out the intervention `Webアプリ` would come before `まず始めに`)
@danswick for review
Ref https://github.com/mapbox/docs-jp/pull/55
> Sort まず始めに (Getting started) to front of topic list

- src/components/browser/__tests__/__snapshots__/browser.test.js.snap
- src/components/browser/__tests__/browser-test-cases.js
- src/components/browser/examples/basic.js
- src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap
- src/components/card-container/examples/basic.js
- src/components/card-container/examples/cols.js
- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/card/examples/basic.js
- src/components/card/examples/no-description.js
- src/components/demo-iframe/examples/basic.js
- src/components/phone/__tests__/__snapshots__/phone.test.js.snap
- src/components/phone/__tests__/phone-test-cases.js
- src/components/phone/examples/basic.js
- src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap
- src/components/related-page/examples/video.js
- src/components/video/__tests__/__snapshots__/video.test.js.snap
- src/components/video/__tests__/video-test-cases.js
- src/components/video/examples/basic.js
- src/helpers/batfish/__tests__/fixtures/data.json
This PR fixes the asset files paths for examples for catalog site. When running the site locally (`npm run start-docs`), it seemed to give a false positive that images are resolving properly -- as all assets are currently broken on the production catalog site. This PR updates all file paths to make sure the assets load correctly on the catalog site (tested by running `npm run build-dics && npm run serve-static-docs` and the test cases app.
> Fix file paths for examples

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/analytics-shell/__tests__/analytics-shell.test.js
- src/components/analytics-shell/analytics-shell.js
- src/components/analytics-shell/examples/basic.js
This PR will remove the `mbxMetadata` object from the window when the AnalyticsShell component unmounts. This will prevent the data object from traveling to another page and writing the wrong data if the component does not load successfully.
> Remove metadata when the component unmounts in AnalyticsShell

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/gl-wrapper/__tests__/__snapshots__/gl-wrapper.test.js.snap
- src/components/gl-wrapper/__tests__/gl-wrapper-test-cases.js
- src/components/gl-wrapper/__tests__/gl-wrapper.test.js
- src/components/gl-wrapper/examples/basic.js
- src/components/gl-wrapper/gl-wrapper.js
This PR:
- Update mapbox-gl-supported to the latest.
- Reworks the message for GLWrapper to use `notSupportedReason` provided by mapbox-gl-supported:
- If IE 11, show our message about IE 11 and Mapbox GL JS support.
- If no WebGL support, show original GLWrapper message.
- else let the user know the reason supplied by `notSupportedReason`. (There can be [many reasons](https://github.com/mapbox/mapbox-gl-supported/blob/214c1ed12dba316a6434469384010948354a8c69/index.js#L18-L30) why Mapbox GL is unsupported that are unrelated to WebGL or IE!)
- Adds an optional prop to GlWrapper: `reason`. This allows us to create (non-rendering) test cases for IE and no WebGL support to generate snapshot tests. This will be helpful in case future mapbox-gl-supported versions change the handling of these …
> Update GLWrapper to check for IE

- CHANGELOG.md
- docs/src/categories.json
- docs/src/pages/guides/lazy.md
- package-lock.json
- package.json
- src/components/lazy/__tests__/__snapshots__/lazy.test.js.snap
- src/components/lazy/__tests__/lazy-test-cases.js
- src/components/lazy/__tests__/lazy.test.js
- src/components/lazy/examples/basic.js
- src/components/lazy/index.js
- src/components/lazy/lazy.js
- src/helpers/batfish/__tests__/fixtures/data.json
_This PR merges in to the `perf` branch #393 ._
This PR adds a new component, `Lazy`. It's a wrapper for https://loadable-components.com/ which is the React team's recommended alternative for lazy loading components server side (`React.lazy` is not supported on the server side by React, yet). 
`Lazy` accepts two props:
- `lazyComponent` a function to import the desired component
- `lazyHeight` the height of the imported component to reduce content layout shift during load.
- `lazyClasses` is an alternative to `lazyHeight` in case the height of the component is variable, you can define classes to best describe the height of the component.
You must define `lazyHeight` or `lazyClasses`.
You can also pass props to `Lazy` that will be passed along to the import component. The lazy props are …
> Add Lazy component

- CHANGELOG.md
- docs/src/categories.json
- package-lock.json
- package.json
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/demo-iframe/__tests__/demo-iframe-test-cases.js
- src/components/demo-iframe/demo-iframe.js
- src/components/demo-iframe/examples/basic.js
- src/components/gl-wrapper/index.js
- src/components/map-wrapper/__tests__/__snapshots__/map-wrapper.test.js.snap
- src/components/map-wrapper/__tests__/map-wrapper-test-cases.js
- src/components/map-wrapper/__tests__/map-wrapper.test.js
- src/components/map-wrapper/examples/basic.js
- src/components/map-wrapper/index.js
- src/components/map-wrapper/map-wrapper.js
_This PR merges into #393._
This PR:
- Renames GLWrapper to MapWrapper to better describe how you can use the component.
- Requires a `height` for MapWrapper to prevent a layout shift while mapbox-supported makes a decision.
- Required a `title` for DemoIframe to improve accessibility.
> Set minHeight in MapWrapper (formerly GLWrapper) and DemoIframe

- docs/src/pages/guides/a11y.md
- src/css/docs-prose.css
- src/css/prism.css
- src/helpers/batfish/__tests__/__snapshots__/navigation.test.js.snap
- src/helpers/batfish/__tests__/fixtures/data.json
This PR improves contrast on a couple elements: 
- adds a new style to set `.prose a code` at a darker blue color
- sets `.namespace` to remove opacity and set a darker color.
1. Run `npm run start-docs`
2. Visit http://localhost:8080/dr-ui/guides/a11y/
3. Run Chrome DevTools Accessibility audit to confirm that there are no color contrast issues.
Fixes https://github.com/mapbox/dr-ui/issues/391
> Improve contrast on syntax highlighting

- CHANGELOG.md
- docs/src/pages/guides/a11y.md
- src/css/docs-prose.css
1. Run `npm ci`
2. Run `npm run start-docs`
3. Navigate to http://localhost:8080/dr-ui/guides/a11y/#heading-with-code-element - You should see that the `code` element in the heading is not colored blue.
Fixes https://github.com/mapbox/dr-ui/issues/408
> Fix CSS for code elements in headings

- CHANGELOG.md
- src/components/code-snippet-title/code-snippet-title.js
This PR makes `filename` required for `CodeSnippetTitle` since the prop puts the `Title` in `CodeSnippetTitle`.
Fixes https://github.com/mapbox/dr-ui/issues/286
> Make `filename` required for `CodeSnippetTitle`

- CHANGELOG.md
- src/components/code-snippet/__tests__/__snapshots__/code-snippet.test.js.snap
- src/components/code-snippet/__tests__/code-snippet-test-cases.js
- src/components/code-snippet/__tests__/code-snippet.test.js
- src/components/code-snippet/code-snippet.js
This PR adds `editClasses` and `editStyles` props to the CodeSnippet component. These props allow us to change the styles and classes for the Edit button so we may change their position on the page.
This PR will also fix the styling of the proptType comments so they will be parsed by our catalog site.
1. `npm ci`
2. `npm start`
3. Visit /CodeSnippet and look at the last test case: CodeSnippet with edit buttons, maxHeight, editClasses, and editStyles. This uses test case shows how we can set the editClasses and editStyles in Help.
> Add editClasses and editStyles props to CodeSnippet

- CHANGELOG.md
- src/components/code-snippet/__tests__/__snapshots__/code-snippet.test.js.snap
- src/components/code-snippet/__tests__/code-snippet-test-cases.js
- src/components/code-snippet/__tests__/code-snippet.test.js
- src/components/code-snippet/code-snippet.js
This PR fixes `CodeSnippet` to allow the `Edit` buttons to appear if the `edit.css` is undefined.
1. npm ci
2. npm start
3. See testcase "CodeSnippet with edit buttons without CSS" in /CodeSnippet
Not applicable.
> The `edit.css` prop is optional when displaying `Edit` in `CodeSnippet`

- src/.eslintrc.json
- src/components/contextless-ios-view-controller-toggle/contextless-ios-view-controller-toggle.js
- src/components/numbered-code-snippet/numbered-code-snippet.js
- src/components/numbered-code-snippet/show-hide-lines.js
- src/components/toggleable-code-block/toggleable-code-block.js
Enforces where React component static properties should be positioned: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/static-property-placement.md
I had noticed that a few (four) components do not use the same patterns as the others, this PR will help keep us consistent.
> Enforces where React component static properties should be positioned

- src/components/code-snippet-title/examples/custom.js
- src/components/code-toggle/__tests__/__snapshots__/code-toggle.test.js.snap
- src/components/code-toggle/__tests__/code-toggle-test-cases.js
- src/components/code-toggle/examples/basic.js
- src/components/contextless-android-activity-toggle/__tests__/__snapshots__/contextless-android-activity-toggle.test.js.snap
- src/components/contextless-android-activity-toggle/__tests__/contextless-android-activity-toggle-test-cases.js
- src/components/contextless-ios-view-controller-toggle/__tests__/__snapshots__/contextless-ios-view-controller-toggle.test.js.snap
- src/components/contextless-ios-view-controller-toggle/__tests__/contextless-ios-view-controller-toggle-test-cases.js
- src/components/toggleable-code-block/examples/basic.js
**Merges into #431**
This PR makes test case toggles interactive, where possible, and adds labels to test cases that are not interactive. This will help make it clear if a change affected the interactivity of these components, especially ahead of reviewing #414 .
Not applicable for this change
> Make code toggles in test cases interactive or label if they are not

- CHANGELOG.md
- src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap
- src/components/related-page/vimeo.js
**This branch merges into #431** 
This PR replaces the `id` in `VimeoPlayImage` with an `aria-label` to prevent duplicated `id`s when more than one instance is on the page.
> Replace `id` with aria-label in VimeoPlayImage

- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/demo-iframe/__tests__/demo-iframe-test-cases.js
- src/components/demo-iframe/__tests__/demo-iframe.test.js
This PR makes the "With token" `DemoIframe` test case a no render test case. The goal of the test case is to prove that the `MapboxAccessToken` prop will be properly merged into the `src` and a snapshot test will help us assert this.
Fixes https://github.com/mapbox/dr-ui/issues/436
> Make "With token" `DemoIframe` a no render test case

- src/helpers/batfish/__tests__/sitemap.test.js
- src/helpers/batfish/sitemap.js
While testing #431, I noticed that in the prepareSitemap Batfish helper that all files that end in `index.js` must have `index.html` appended to the path (not just the root index.js file). This PR makes that fixes and adds a test case to support it.
Before this fix, the test case would return the following paths to ignore:
```json
["/_site/index.html", "/_site/core/", "/_site/java/", "/_site/core/guides/hidden/"]
```
This would result in the sitemap excluding everything under `/_site/core/` and `/_site/java/` since it uses globs. This is not what we want. We only want the `index.html` to be removed from the sitemap, not all pages under those directories.
With the fix, the paths are more specific:
```json
["/_site/index.html", "/_site/core/index.html", "/_site/java/index.html", …
```
> Fix prepareSitemap function to append index.html to files ending in index.js

- .remarkrc.js
This PR fixes the siteOrigin in the remark config to fix the broken tests seen in https://github.com/mapbox/dr-ui/pull/445
> Fix siteOrigin

- CHANGELOG.md
- src/components/search/search.js
Adds to the default [Swiftype connector configuration](https://github.com/mapbox/dr-ui/blob/940a447076ecec52a6fc74d943af1dad32b26fdd/src/components/search/search.js#L116) to handle possible spelling errors in search queries. The [Swiftype API supports a "spelling" option](https://swiftype.com/documentation/site-search/searching/spelling), but it is not supported out of the box in the elastic search-ui library we use for our search. However, [search-ui has a `beforeSearchCall` hook](https://github.com/elastic/search-ui/blob/cb774e2ab1e6831ff40523c62d76b57d4c71ed5f/ADVANCED.md#api-config) that can append arbitrary options before a search call is made.
There are three options for how we could handle spelling issues:
1. `strict`: Returns a spelling correction value when there are no results …
> For searches with no results, retry if Swiftype thinks there is a spelling error

- CHANGELOG.md
- src/helpers/version-sort.js
- tests/version-sort.test.js
Fixes #463.
I tested this solution by rebuilding NavSDK "API Reference" page https://docs.mapbox.com/ios/navigation/api-reference/ with these changes.
**Before:** 
**After:** 
> Fix `sortVersions` for prerelease versions greater than 10.

- CHANGELOG.md
- package-lock.json
- package.json
This PR will bump @mapbox/rehype-prism@0.7.0 and prismjs@1.24.0 to fix a security issue with prismjs (ref #465)
> @mapbox/rehype-prism@0.7.0 and prismjs@1.24.0

- CHANGELOG.md
- src/components/video/video.js
This PR fixes a bug with the Video component, where `play` should be handled as a promise.
Fixes #458 
1. npm start
2. visit /Video test case
3. interact with the videos to make sure you can click the video to pause/play it
> Handle `Video` play as a promise

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/analytics-shell/__tests__/analytics-shell.test.js
- src/components/analytics-shell/analytics-shell.js
This PR will automatically add Sentry's tracing integration to the AnalyticsShell Sentry initialization via a new prop `sentryPerformance`. You can disable tracking with an empty object `<AnalyticsShell sentryPerformance={{}} />`.
When we are ready to enable Sentry performance trial, all sites will be ready to launch. 
This will be difficult to test since we don't have the trial yet, but since tracing is automatic I think it should be ok!
https://docs.sentry.io/platforms/javascript/performance/
> Add Sentry tracing with new `sentryPerformance` prop on AnalyticsShell

- CHANGELOG.md
- package-lock.json
- package.json
- src/helpers/version-sort.js
This PR switches the sortVersions function to a common JS module. Before #457, babel was converting the module, but since this module is used by Batfish (and only accepts CJS at this time), we'll want this module to be CJS.
> Make sortVersions a common JS module

- CHANGELOG.md
- src/components/feedback/__tests__/category-like.test.js
- src/components/feedback/feedback.js
This PR updates the Feedback component to only send an event to Sentry if feedback exists.
For testing data sent to Segment/Sentry:
1. `npm ci`
2. `npm run start`
3. Visit the Feedback test cses
4. Open the #bots channel in Slack (to see Segment events) and the docs-feedback Sentry project.
5. Click through Feedback component and watch events come through in #bots and the final "Submit feedback" will trigger a new Sentry issue (if you submit text feedback). There should **not** be a Sentry issue for "I like" feedback that does not contain text feedback.
Not needed for this change.
> Only send feedback to Sentry if it exists

- CHANGELOG.md
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/navigation-accordion/__tests__/navigation-accordion.test.js
- src/components/navigation-accordion/navigation-accordion.js
This PR fixes an issue in NavigationAccordion, when a page does not have a parentPage then the sidebar will fail. 
- 3249699 - in this commit I prove the failure by adding a test case and mocking the document width. The result is a null snapshot because the component returns errors. Note: needed to move the `isMM` const inside the React component to properly mock the width.
- 7f19b62 - in this commit, I fix the failure by checking that the parentPage exist. The result is a snapshot with NavigationAccordion markup.
Fixes https://github.com/mapbox/dr-ui/issues/478
> Check that `parentPage` exists in `NavigationAccordion`

- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/level-indicator/__tests__/__snapshots__/level-indicator.test.js.snap
- src/components/level-indicator/level-indicator.js
This PR merges into #481 and updates LevelIndicator to Assembly v1. This PR also removes unused classes `inline-block` and `align-middle`.
> [Assembly v1] LevelIndicator

- src/components/download-button/__tests__/download-button-test-cases.js
- src/components/download-button/download-button.js
- src/test-cases-app/files/sample.geojson
Fixes text for GeoJSON download buttons so they appear as "GeoJSON" rather than "GEOJSON". Adds a test case and sample file. 
- Run test cases app and confirm GeoJSON appears as expected 
- Make sure download functionality for GeoJSON works
> Fix DownloadButton for GeoJSON

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/demo-iframe/__tests__/__snapshots__/demo-iframe.test.js.snap
- src/components/error-boundary/__tests__/__snapshots__/error-boundary.test.js.snap
- src/components/map-wrapper/__tests__/__snapshots__/map-wrapper.test.js.snap
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js
- src/components/note/__tests__/__snapshots__/note.test.js.snap
- src/components/note/note.js
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/overview-header/__tests__/overview-header-test-cases.js
- src/components/overview-header/overview-header.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/product-menu/__tests__/product-menu-test-cases.js
- src/components/product-menu/product-menu.js
- src/components/tag/__tests__/__snapshots__/tag.test.js.snap
- src/components/tag/examples/custom.js
- src/components/tag/tag.js
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/__tests__/themes-test-cases.js
- src/components/themes/__tests__/themes.test.js
- src/components/themes/themes.js
- src/css/docs-prose.css
This PR merges into #481 and updates Themes, Note, and Tag with Assembly v1. Since Themes directly affects Note and Tag, it would have been difficult to review without updating all three at once.
- Replaces hex colors with Assembly classes in theming. Now that we have more color options, we can safely use Assembly colors across the board. We used hex to improve color contrast.
- Introduces a breaking change to `Tag`. Replaced `customStyles` prop in `Tag` with `customBorder`, `customColor,` and `customBackground`. The new props accept class names. Since we can safely use Assembly color classes, this change will make custom tags consistent in also using color classes. It does not appear that this feature is in use right now on any live production site. 
---|---
Use the …
> [Assembly v1] Themes, Note, Tag

- CHANGELOG.md
- src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap
- src/components/card-container/card-container.js
- src/components/card-container/examples/cols.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/example-index.js
- src/components/page-layout/page-layout.js
This PR merges into #481 and updates the CardContainer component to Assembly v1.
---|---
> [Assembly v1] CardContainer

- src/components/feedback/__tests__/__snapshots__/category-confusing.test.js.snap
- src/components/feedback/__tests__/__snapshots__/category-like.test.js.snap
- src/components/feedback/__tests__/__snapshots__/category-problem.test.js.snap
- src/components/feedback/__tests__/__snapshots__/confirmation.test.js.snap
- src/components/feedback/__tests__/__snapshots__/contact-support.test.js.snap
- src/components/feedback/__tests__/__snapshots__/logged-in.test.js.snap
- src/components/feedback/feedback.js
This PR merges into https://github.com/mapbox/dr-ui/pull/481 and updates the Feedback component to Assembly v1.
> [Assembly v1] Feedback

- babel.config.js
We recently [enabled es modules](https://babeljs.io/docs/en/babel-preset-env#modules) in #457, but https://github.com/mapbox/react-test-kitchen (the system for our test cases) works best with common js. This PR updates the `test` babel environment to not preserve es modules.
I noticed this when trying to interact with the /Search test case and the dynamic import failed to load.
1. Run: `nvm use && npm ci && npm start`
2. Visit: /Search test cases
3. Interact with search, there should be no errors logged to the console (re: the dynamic import should load as expected).
> Do not preserve es modules in test environment

- CHANGELOG.md
- src/components/navigation-accordion/__tests__/navigation-accordion.test.js
- src/components/navigation-accordion/navigation-accordion.js
While working on updating NavigationAccordion to Assembly v1, I noticed that the basic test case was broken. When I click the chevron-down icon, the component failed. This PR:
- Adds a test to prove the bug: df4fb4a (the [Travis build fails](https://app.travis-ci.com/github/mapbox/dr-ui/builds/237641095#L836) with `TypeError: Cannot read property 'indexOf' of undefined`)
- Fixes the bug and adds test to assert the fix: c544e8a
1. `nvm use && npm ci && npm start`
2. Visit `/NavigationAccordion` test cases
3. Toggle the chevron-down icons on all examples: you should not see any errors
> Handle NavigiationAccordion when there is no `activeItem`

- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/product-menu/product-menu.js
This branch updates ProductMenu to Assembly v1 (and does some clean up 💆)
> [Assembly v1] ProductMenu

- src/components/numbered-code-snippet/__tests__/__snapshots__/numbered-code-snippet.test.js.snap
- src/components/numbered-code-snippet/numbered-code-snippet.js
- src/components/numbered-code-snippet/show-hide-lines.js
- src/components/toggleable-code-block/__tests__/__snapshots__/toggleable-code-block.test.js.snap
This PR merges into https://github.com/mapbox/dr-ui/pull/481 and updates the NumberedCodeSnippet component to Assembly v1.
> [Assembly v1] NumberedCodeSnippet

- src/components/phone/__tests__/__snapshots__/phone.test.js.snap
- src/components/video/__tests__/__snapshots__/video.test.js.snap
- src/components/video/video.js
This PR merges into https://github.com/mapbox/dr-ui/pull/481 and updates the Video component to Assembly v1.
> [Assembly v1] Video

- CHANGELOG.md
- src/components/feedback/__tests__/__snapshots__/contact-support.test.js.snap
- src/components/feedback/categories.js
This PR moves the "I like..." category in `Feedback` to the button of the list.
Fixes https://github.com/mapbox/dr-ui/issues/515
1. `nvm use && npm ci && npm start`
2. Visit /Feedback test case
3. Click "Share feedback", the "I like.." button should be the last button option.
4. Test to make sure feedback is sent as expected: submit feedback, check payload in #bots Slack channel and that an issue is opened in Sentry.
> Move I like... category to bottom of list in Feedback

- CHANGELOG.md
- src/components/navigation-accordion/navigation-accordion.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/__tests__/page-layout.test.js
- src/components/page-layout/components/guide-group-index.js
This PR updates `GuideGroupIndex` in `PageLayout` to use `CardContainer` to display full width cards. This helps reduce patterns and improve consistency. This PR will also generate a snapshot test for the grouped guides test case.
This PR will also fix an accessibility issue with the NavigationAccordion where the subpages were not properly nested: https://github.com/mapbox/dr-ui/pull/519/commits/6eb9fbf1f3a0cfd0da88da168be9e60bddd14883
Fixes #509 
1. `nvm use && npm ci && npm start`
2. Visit /PageLayout test case, specifically `Page layout: group index.`
3. `npm run start-docs`
4. Visit http://localhost:8080/dr-ui/guides/grouped-guides/
> Updates `GuideGroupIndex` in `PageLayout` to use `CardContainer` to display full width cards

- src/plugins/make-table-scroll.js
This PR updates the make-table-scroll plugin to Assembly v1.
@malwoodsantoro this plugin is included in the `batfish.config.json` for each site. It wraps a div around each table and adds the `overflow-auto` class so that tables, especially on smaller screens, will scroll.
Not needed for this change.
> Update class in make-table-scroll plugin

- src/components/note/__tests__/__snapshots__/note.test.js.snap
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/themes.js
- src/helpers/batfish/__tests__/fixtures/data.json
I was noticing that the font color for the default theme seemed to dark. I think we should switch it to `color-text`.
Stage | Image
---|---
Current | ![image](https://user-images.githubusercontent.com/2180540/135120518-39ca6c58-0cb6-4ba2-8bb9-794f84e47aad.png) 
Proposed | ![image](https://user-images.githubusercontent.com/2180540/135120441-25cd8f0d-98c7-4b2c-bb96-6e5b6bc4661c.png)
Visit /Note and /Themes test cases
> [Assembly v1] Update default theme to use `color-text`

- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/overview-header/overview-header.js
- src/helpers/batfish/__tests__/fixtures/data.json
This PR fixes two minor design features with OverviewHeader:
1. Sets the bottom border color over OverviewHeader to match the border color of h2 (gray-light)
Stage | Image
---|---
Current | ![image](https://user-images.githubusercontent.com/2180540/134920012-459d739e-3b6d-49c6-86fb-99db133d5810.png)
Proposed | ![image](https://user-images.githubusercontent.com/2180540/134920107-ab93d6cd-6813-488a-9f32-73d0dd3c97bf.png)
2. Sets the check icon color when `lightText` is defined:
Stage | Image
---|---
Current | ![image](https://user-images.githubusercontent.com/2180540/134919826-ed00c303-725e-4175-801b-863e16df6d84.png)
Proposed | ![image](https://user-images.githubusercontent.com/2180540/134919893-bb2af85b-fb42-4bbc-b7e9-f96b655eb3e3.png)
Visit the /OverviewHeader testcase and catalog page …
> [Assembly v1] Fix border color and set icon color for `lightText` on `OverviewHeader

- docs/src/pages/guides/test-pages/a11y.md
- docs/src/pages/guides/test-pages/headings.md
- docs/src/pages/guides/test-pages/index.md
- src/css/docs-prose.css
- src/helpers/batfish/__tests__/__snapshots__/navigation.test.js.snap
- src/helpers/batfish/__tests__/fixtures/data.json
- src/helpers/batfish/__tests__/sitemap.test.js
This PR will add back `padding-top` to docs-prose.css to fix an issues seen across several sites. This PR also makes a small adjustment to the catalog site:
- Adds "Test pages" grouped guide section
- Moves the accessibility test page under the Test pages group
- Add a Headings test page which allowed me to reproduce and confirm that the heading bug was fixed.
1. Run `npm run start-docs`
2. Visit http://localhost:8080/dr-ui/guides/test-pages/headings/
3. Confirm that the padding between the h2 and the border-top is there!
Not required for this change.
> [Assembly v1] h2 fix

- docs/src/css/site.css
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- src/components/page-layout/components/sidebar.js
While reviewing /mapbox-gl-js/style-spec/layers/#symbol I noticed that the right navigation bar did not have a scrollbar. (For reference https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol does!) This is because I missed updating the deprecated viewport and scroll classes 😄
> [Assembly v1] Replace viewport and scroll classes in PageLayout

- src/components/demo-iframe/__tests__/demo-iframe-test-cases.js
- src/components/demo-iframe/demo-iframe.js
Addresses https://github.com/mapbox/dr-ui/issues/505
> Add optional height prop to DemoIframe

- .travis.yml
- src/components/page-layout/components/content.js
Adds a call to action to Sign Up to `PageLayout`, visible when the user is signed out.  It is displayed in the sidebar on large screens.  On smaller screens it is shown BOTH below the page index AND after the content.
Run dr-ui locally and inspect the `PageLayout` examples.  Change viewport width to see the two different display modes.
> Add signup banner

- CHANGELOG.md
- package-lock.json
- src/components/search/search-box.js
- src/components/search/search-modal.js
- src/components/search/search-result.js
Improves the UX and styling of the search modal and search results pane.
- When the search modal is opened, uses `backdrop-filter` to blur the background instead of graying it out
- Removes loading spinner from search box and results pane (an overlay shown on loading was causing an unsightly flash
- Lowers debounce for the API call to Swifttype from `1500` to `200`, eliminating a lengthy delay for the user
- Removes a default `box-shadow` on the text input which was causing the input to appear as a few pixels less wide than the results pane... now both have the same box-shadow
- Styling updates: text in the input and the results are smaller, highlighted words appear in bold, underlined, and a different color
Run `dr-ui` locally, use the search component to try out some search strings. …
> improve search

- CONTRIBUTING.md
- scripts/create-pull-request.sh
Adds a simple shell script for automating pull requests on docs sites after a new version of dr-ui is released (uses git github-cli commands)
Updates `CONTRIBUTING.md` to document how to use the PR creation script.
> add pr script

- src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap
- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/card/card.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- src/components/page-layout/components/example-index.js
Adds `link` prop to `Card` used in example listings.  This adds `target` attributes to the `a` tag used on the cards, and turns them into external links when clicked (versus navigating to a page on the docs site).
Also adds an external link icon next to the title
Once merged we can cut a new version 5.1.8.
> External link cards

- src/components/search/search-box.js
- src/components/search/search-provider.js
Fixes a bug where the search modal would open on page navigation after it had already been loaded and dismissed once.
https://mapbox.atlassian.net/jira/software/c/projects/MARKETING/boards/254?modal=detail&selectedIssue=MARKETING-1627
> fix search modal appearing on page navigation

- package-lock.json
- package.json
- src/helpers/batfish/__tests__/filters.test.js
- src/helpers/batfish/__tests__/fixtures/data.json
- src/helpers/batfish/filters.js
- use 'order' to order GL JS examples
- 5.1.12
- fix collision between 'order' and 'level'
- 5.1.13
> upgrade 5.1.12

- package-lock.json
- package.json
- src/components/back-to-top-button/__tests__/__snapshots__/back-to-top-button.test.js.snap
- src/components/back-to-top-button/back-to-top-button.js
- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/download-button/__tests__/__snapshots__/download-button.test.js.snap
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- Bumps `mr-ui` to the latest version `2.4.0` (no changes are introduced, this is just to stay current)
- Fixes the `ariaLabel` property warning which has been showing up on docs sites via `PageLayout` (the offending component was `BackToTopButton, which included an `ariaLabel` prop that should have been `aria-label`.  This is apparently an exception to the rule of using camelcase for html attributes in react.
> bump mr-ui to 2.4.0, fix ariaLable console warning

- package-lock.json
- package.json
- src/components/back-to-top-button/__tests__/__snapshots__/back-to-top-button.test.js.snap
- src/components/back-to-top-button/back-to-top-button.js
- src/components/card/__tests__/__snapshots__/card.test.js.snap
- src/components/download-button/__tests__/__snapshots__/download-button.test.js.snap
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- src/components/page-layout/components/signup-banner.js
Merge after #555 
- Adds some additional markup to create a better layout for the two CTA buttons (Sign up and Discord) when appearing at the bottom of a wide layout.
- Instead of showing up stacked, with lots of empty space, they now appear as 50% width tiles with gutter.
> Fix cta layout

- babel.config.json
The updates were causing an esm-style import statement to be added to the top of a cjs file
> restore babel present-env options

- package-lock.json
- package.json
- src/components/search/search-box.js
Rolls back `react-search-ui` dependencies to `1.7.0`, the latest version (`1.20.2`) was causing a crash when a search item was selected.
> rollback react-search-ui dependencies to 1.7.0

- src/components/on-this-page/on-this-page.js
- adjusts the default `topOffset` prop of `OnThisPage` to account for an additional 70px caused by the sticky header.
- this fixes a bug where the "current" section of a docs page was not highlighted at the correct time in the right sidebar when deep linking or scrolling through a page.
> adjust onthispage topoffset to account for sticky header

- src/components/error-boundary/__tests__/__snapshots__/error-boundary.test.js.snap
- src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap
- src/components/note/__tests__/__snapshots__/note.test.js.snap
- src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap
- src/components/tag/__tests__/__snapshots__/tag.test.js.snap
- src/components/tag/tag.js
- src/components/themes/__tests__/__snapshots__/themes.test.js.snap
- src/components/themes/themes.js
Restores `theme` color and background color classnames which were lost in the recent redesign. The component was refactored before the decision to use `mbx-assembly-docs` for custom colors, but was never reset.  `theme.js` colors are used by both `Note` and `Tag` This was causing some `Note` components to show up with no background.
> restore theme color classnames

- src/components/video-modal/video-modal.js
- Reduces the modal width to 65vw instead of 80, which is more reasonable to keep the video in view when viewing the docs on a laptop.
- Refactors the styling to use the previous approach to maintaining the aspect ratio (uses % based padding so that the height does not need to be defined anywhere)
> update video modal

- src/components/search/search-modal.js
Removes calls to `mr-ui` `getWindow()` util which causes issues when rendering SSR pages and is being removed from `mr-ui` in https://github.com/mapbox/mr-ui/pull/216
> remove calls to mr-ui getWindow util

- src/components/search/search-modal.js
Updates the search modal to use the same styling as `mr-ui/modal` for 
consist UX across the site. (e.g. `VideoModal` uses `mr-ui/modal` and we 
don't want two different modal experiences)
> update search modal background to match mr-ui/modal

- src/components/index-card/__tests__/__snapshots__/index-card.test.js.snap
- src/components/index-card/index-card.js
Updates the assembly classes used on the title in `IndexCard`, adding 6 
pixels of spacing when the content wraps to mutliple lines.
Before
After
> style index card title/tag for proper vertical spacing when wrapped

- src/components/breadcrumb/breadcrumb.js
- src/components/overview-header/__tests__/overview-header-test-cases.js
In `Breadcrumb`, uses the `index` as the react element key instead of `link.title` which could be 
undefined.
This fix will prevent unique key warnings from appearing in the console during builds if there are 
pages with no title (e.g. when building the docs for mr-ui, as changelog.md generates a page but 
has no title)y
> fix breadcrumb key

- src/components/feedback/feedback.js
- src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
- src/components/page-layout/components/content.js
- This change adds some intelligence to the `<ContentWrapper>` component to check props for the `layoutConfig.contentType` to determine if the location in which the component is being rendered is an example page or a playground page.
- If it is either of these types, the value is passed into the `type` prop of the `<Feedback>` component.  If it's not either of these values, an undefined value is passed into the type and `<Feedback>`'s default prop type of `page` is used.  
- Ensure that your local Dr-UI repo is connected (via `npx link`) to the playgrounds repo, and the GL-JS-docs repo.  
- Pull down this branch, run `npm run build` in dr-ui
- Start the connected playground repo and check the output of the feedback module on a playground page to ensure it reads 'Was this playground …
> Andrew/add playground type To Feedback Component

- package.json
`@mapbox/mbx-assembly-docs@"^0.1.0` caused a dependency resolution issue due to the way npm treads 0 major versions.
> update mbx-assembly-docs peer dependency version

- src/components/overview-header/__tests__/overview-header-test-cases.js
In the test cases for OverviewHeader, we were passing in 
GettingStartedIcon instead of <GettingStartedIcon/> causing a console 
error and the `titleIcon` to not show.
> Pass in GettingStartedIcon instance to OverviewHeader test case

- src/components/index-card/index-card.js
This PR introduces the `colSize` prop for `<IndexCard>` which gives the opportunity to set custom col layouts with the index card component.  `colSize` is a fraction based on [Assembly grid classes](https://labs.mapbox.com/assembly/documentation/#Grid).  The component consumes the fraction (for example `1/3`) and will set the width of the indexCard on medium to xl screens to 1/3.  Medium screen sizes (`colsMed`) get a fraction with the denominator - 1.  If no `colSize` is set, layout of IndexCards defaults to 1/4. 
Create a component in a consuming site that looks like this.. 
```
<IndexCard
key={3}
colSize={'1/3'}
title={'Ticket Portal'}
text={'Support Plan subscribers can submit and view their technical support tickets here.'}
links={[
{ title: 'See your open tickets', link: …
```
> Update index card
