mapbox/dr-ui

package-lock.json, package.json, src/components/topbar-sticker/__tests__/topbar-sticker-test-cases.js, src/components/topbar-sticker/topbar-sticker.js
Closes #1.
I named it TopbarSticker because it makes a topbar stick.
The existing test case is for display purposes only. Other test cases could be written for unit tests.
Here it is at work:
(Doesn't stick on narrow screens.)
@colleenmcginnis for review.
=> Add TopbarSticker component

src/components/sectioned-navigation/__tests__/sectioned-navigation-test-cases.js, src/components/sectioned-navigation/sectioned-navigation-section.js, src/components/sectioned-navigation/sectioned-navigation.js
Closes #12.
I built in a couple of options that I thought might come in handy:
- Overall title is optional.
- Section titles might not be links.
- Maybe you don't want to include section counts.
@colleenmcginnis for review.
=> Add SectionedNavigation component

package-lock.json, package.json, src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js, src/components/navigation-accordion/navigation-accordion.js, src/components/navigation-dropdown/__tests__/navigation-dropdown-test-cases.js, src/components/navigation-dropdown/navigation-dropdown.js
Closes #7 
`NavigationAccordion`:
`NavigationDropdown`:
=> Add NavigationAccordion and NavigationDropdown

.gitignore, README.md, package-lock.json, package.json, scripts/build-package.js
Adds [build script from mr-ui](https://github.com/mapbox/mr-ui/blob/master/scripts/build-package.js), updates readme, and prepares for `dr-ui` name change.
=> Prepare for initial release

package-lock.json, package.json, src/components/back-to-top-button/back-to-top-button.js, src/components/code-toggle/code-toggle.js, src/components/navigation-accordion/navigation-accordion.js, src/components/navigation-dropdown/navigation-dropdown.js, src/components/overview-header/overview-header.js, src/components/product-menu-dropdown/product-menu-dropdown.js, src/components/product-menu/product-menu.js, src/components/toggleable-code-block/toggleable-code-block.js
Transitions from individually packaged mapbox-react-components to the new mr-ui monopackage and updates affected components.
=> mapbox-react-components 🔜 mr-ui

src/components/navigation-accordion/navigation-accordion.js
=> Fix NavigationAccordion hover bug

src/css/docs-prose.css
Closes #25
There's not much in here now, but we can add more if necessary later.
=> Add shared CSS for docs prose

src/components/book-image/book-image.js, src/components/note/__tests__/note-test-cases.js, src/components/note/note.js
=> Add Note and BookImage components

.eslintignore, package-lock.json, package.json, scripts/build-package.js, src/plugins/add-links-to-headings.js
Closes #34 
@danswick I got some precommit errors that I wasn't sure how to resolve so I added this file to `.eslintignore` so I could push changes and you could take a look. Let me know what you think!
=> Add rehype plugin to add links to headings in md files

CHANGELOG.md, src/components/product-menu/__tests__/product-menu-test-cases.js, src/components/product-menu/product-menu.js
=> Add options for styling ProductMenu popover trigger

CHANGELOG.md, src/components/note/note.js
⚠️ 🔍 super subtle changes  🔍 ⚠️
fixes #77
=> adds borderRadius; makes text color AA accessible

CHANGELOG.md, package-lock.json, package.json, src/plugins/make-table-scroll.js
=> adds make-table-scroll plugin

CHANGELOG.md, src/css/prism.css
Fixes https://github.com/mapbox/dr-ui/issues/106
=> Add prism.css to create shared syntax styles used commonly across sites

CHANGELOG.md, src/components/card-container/card-container.js, src/components/card/card.js, src/components/examples-page/__tests__/examples-page-test-cases.js
For extra testing, I created a branch in help called `DNM-cardcontainer-example` that uses these components.
fixes #92
=> [Card/CardContainer] Add new styles for fullwidth cards

CHANGELOG.md, src/components/overview-header/overview-header.js
fixes https://github.com/mapbox/dr-ui/issues/110
=> Add `mb24` to `OverviewHeader`

CHANGELOG.md, src/helpers/version-sort.js, tests/version-sort.test.js
fixes https://github.com/mapbox/ios-sdk/issues/678
=> fix prerelease order in sortVersion helper function

CHANGELOG.md, package-lock.json
=> Update security vulnerabilities in dependencies

.travis.yml, CHANGELOG.md, package-lock.json, package.json, src/test-cases-app/test-cases-app.js
Updates our search provider to get various bug fixes and get on the latest stable version. There have been breaking changes to releases since we last updated, but none that affect the parts of the components we are using.
=> [search] update to v1.0.0 of search-ui

CHANGELOG.md, src/components/video/__tests__/__snapshots__/video.test.js.snap, src/components/video/__tests__/video-test-cases.js, src/components/video/__tests__/video.test.js, src/components/video/video.js
Ref https://github.com/mapbox/documentation/issues/254
Creates a `Video` component that will autoplay on loop.
=> Create a video component

CHANGELOG.md, src/components/highlight/__tests__/__snapshots__/highlight.test.js.snap, src/components/highlight/__tests__/highlight-test-cases.js, src/components/highlight/__tests__/highlight.test.js, src/components/highlight/css.js
This PR creates a CSS highlighter option for the [highlight component](https://github.com/mapbox/dr-ui/tree/master/src/components/highlight) 🖍 
@katydecorah to review please!
=> Adds a CSS highlighter option to highlight component

src/components/example-image/index.js, src/components/glossary-image/index.js, src/components/related-page/index.js
When I ran `npm run build` these indices were generated. We should commit them!
=> add missing indices

.github/PULL_REQUEST_TEMPLATE.md
All our components should score 100% on Accessibility - I think we should add this to the PR checklist to hold ourselves accountable.
=> Update PR checklist to include Accessibility/Lighthouse score

CHANGELOG.md, src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap, src/components/related-page/related-page.js
Fixes #237 
> ![image](https://user-images.githubusercontent.com/2180540/73289908-7b3d4180-41cb-11ea-91fe-342dd3cb5a20.png)
_IE 11_
=> fixes overflow issue in IE11 for RelatedPage

src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap, src/components/related-page/__tests__/related-page-test-cases.js
=> Replace description with children in RelatedPage test case

package-lock.json, package.json, src/components/page-layout/components/sidebar.js
This PR merges into #317 with a small change to make the sticky sidebar full height when the topbar is not sticky.
=> [layouts] Fix sidebar height when topbar is not sticky

CHANGELOG.md, package-lock.json, package.json, src/components/feedback/feedback.js
This PR:
- Adds a referrer tag to the feedback module
- Bumps sentry version to 5.24.2
=> Add a referrer tag to the Feedback module; bump Sentry version

src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap, src/components/navigation-accordion/__tests__/navigation-accordion-test-cases.js, src/components/navigation-accordion/__tests__/navigation-accordion.test.js
This PR merges into #431 and fixes the NavigationAccordion test cases:
1. Use the example/basic.js component as the basic test case
2. Add snapshot for withTags test case
=> Fix NavigationAccordion tests

package-lock.json, package.json, src/components/search/search-box.js
This PR fixes an error in the Search component when clicking the site toggle.
cc @colleenmcginnis
=> Fix props on search toggle

src/components/back-to-top-button/__tests__/__snapshots__/back-to-top-button.test.js.snap, src/components/back-to-top-button/back-to-top-button.js, src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
This PR merges into #481 and updates BackToTopButton to Assembly v1.
=> [Assembly v1] BackToTopButton

src/components/card-container/__tests__/__snapshots__/card-container.test.js.snap, src/components/card/__tests__/__snapshots__/card.test.js.snap, src/components/card/card.js, src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
This PR merges into #481 and updates the Card component to Assembly v1.
---|---
=> [Assembly v1] Card

src/components/phone/__tests__/__snapshots__/phone.test.js.snap, src/components/phone/phone.js
This PR merge into #481 and updates the Phone component to Assembly v1.
Note: the test cases app uses the Video component, which hasn't been updated yet (you may see a mis-aligned video play button).
---|---
=> [Assembly v1] Phone

src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap, src/components/overview-header/overview-header.js
This PR updates OverviewHeader to Assembly v1.
=> [Assembly v1] OverviewHeader

src/components/on-this-page/__tests__/__snapshots__/on-this-page.test.js.snap, src/components/on-this-page/examples/basic.js, src/components/on-this-page/helpers.js
This PR merges into https://github.com/mapbox/dr-ui/pull/481 and updates the Feedback component to Assembly v1.
=> [Assembly v1] OnThisPage

src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap, src/components/navigation-accordion/navigation-accordion.js, src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap
This PR updates NavigationAccordion to Assembly v1.
~~Note: The basic test cases is broken but will be fixed in #495~~
=> [Assembly v1] NavigationAccordion

CHANGELOG.md, package-lock.json, package.json
This PR updates to mr-ui@1.1.0
https://github.com/mapbox/mr-ui/blob/main/CHANGELOG.md
It seems the updates to Popover does not affect dr-ui.
=> [Assembly v1] Update mr-ui@1.1.0

src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap, src/components/search/__tests__/__snapshots__/search.test.js.snap, src/components/search/__tests__/results.js, src/components/search/search-box.js, src/components/search/search-result.js
This PR updates the Search component to Assembly v1.
~~🛑 This PR is blocked by #498~~ 
=> [Assembly v1] Search

src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap, src/components/related-page/__tests__/__snapshots__/related-page.test.js.snap, src/components/related-page/related-page.js
This PR merges into https://github.com/mapbox/dr-ui/pull/481 and updates the RelatedPage component to Assembly v1.
=> [Assembly v1] RelatedPage

docs/src/components/component-example.js, docs/src/components/component-section.js, docs/src/pages/components/index.md, src/css/docs-prose.css
Updates catalog site to Assembly v1 with codemod script. Fixes two accessibility issues 1) color contrast for required tag in the docs 2) darkens links in overview header.
=> [Assembly v1] Update catalog site

CHANGELOG.md, package-lock.json, package.json
Updated changelog to reflect new version with Mapbox Developers Discord call-to-action button on right aside.
=> Con changelog

docs/batfish.config.js, docs/src/components/wrapper.js, docs/src/css/site.css, package-lock.json, package.json, scripts/deploy-to-staging.sh, src/components/error-boundary/__tests__/__snapshots__/error-boundary.test.js.snap, src/components/navigation-accordion/__tests__/__snapshots__/navigation-accordion.test.js.snap, src/components/note/__tests__/__snapshots__/note.test.js.snap, src/components/note/__tests__/note-test-cases.js, src/components/overview-header/__tests__/__snapshots__/overview-header.test.js.snap, src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap, src/components/page-layout/components/content.js, src/components/page-layout/components/example-index.js, src/components/page-layout/components/sidebar.js, src/components/page-layout/page-layout.js, src/components/product-menu/__tests__/__snapshots__/product-menu.test.js.snap, src/components/search/__tests__/__snapshots__/search.test.js.snap, src/components/search/__tests__/search-test-cases.js, src/components/search/search-box.js, src/components/search/search-modal.js, src/components/search/search.js, src/components/tag/__tests__/__snapshots__/tag.test.js.snap, src/components/tag/examples/custom.js, src/components/tag/tag.js, src/components/themes/__tests__/__snapshots__/themes.test.js.snap, src/components/themes/__tests__/themes.test.js, src/components/themes/themes.js, src/test-cases-app/index.html
Changes in support of the docs landing page redesign
- [update tag design](https://github.com/mapbox/dr-ui/commit/0667bd7ceecd148b6ad7281fb81fdbcf0ba47002)
- [add placeholder prop on search box](https://github.com/mapbox/dr-ui/commit/7f781f7940800ad41ae582c46ddc1ad04f881ff5)
- [add bottom padding to filter sidebar menu](https://github.com/mapbox/dr-ui/commit/22c5ecc7f67bfeb02cce3ab4590e96fca137c806)
- [adjust sticky sidebars to fit new fixed header](https://github.com/mapbox/dr-ui/commit/0647b3467f17e367b9e15879cc0182b6c7160dfc)
- Update `Search` component styles
- Add loading spinners to search inputs while fetching data
- Use `mbx-assembly-docs` as a peer dependency, implement new mbx-assembly-docs classes for tags
=> Docs Landing Page Redesign

src/components/page-layout/__tests__/__snapshots__/page-layout.test.js.snap, src/components/page-layout/components/content.js, src/components/page-layout/components/sidebar.js, src/components/page-layout/page-layout.js, src/css/docs-prose.css
Styling fine tuning to ensure precise positioning, height, margins, and padding of the sidebar and aside.  
- Ensures optimal presentation of the content when scrollbars are visible.
- Ensures ample padding at the top and bottom of the scrolling sidebar and aside.
=> improve sidebar and aside scroll UX
